logging:
  config: classpath:log4j2.xml
  level:
    net.czqu.openserver: trace
server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://alpha.common.czqu.net:13306/openIM_v2?useSSL=false
    username: root
    password: openIM123
  redis:
    database: 0
    host: alpha.common.czqu.net
    port: 16379
    timeout: 3000
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0